apiVersion: "v1"
kind: "Service"
metadata:
  name: "microservicesaddressvalidate-service"
  namespace: "default"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8089
  selector:
    app: "microservicesaddressvalidate"
  type: "LoadBalancer"
  loadBalancerIP: ""